### ISSUE TITLE
Filmer - Card for display

### ISSUE THREAD

**Issue by MatsJoh50** [Kookiie88/A4_biografSajt#39]
Build a card to display the most curtial information to choose a movie.
This card will be able to print at several places on the platform.

DoD:
The card should match the wireframe and overall design.
It will show:

- [ ] Title of movie
- [ ] Lengh of play
- [ ] Shortend description (40words?)
- [ ] "Book now" button

**Comment by Weeezzt** [comment]
Not sure we said we should have length of play... Not in the built api

**Comment by Weeezzt** [comment]
![Image](https://github.com/Kookiie88/A4_biografSajt/assets/144351044/f9cb4136-c13f-4e55-9ac5-1c41dad5bd16)

Looks good
